"""
Generate the inlined Figma icon modules from the committed SVG exports, one per revision.

## Why generate instead of hand-writing

The brief forbids invented SVGs, and hand-transcribing a path is exactly that — a redrawing that
happens to look similar. Generating the module from `assets/images/figma-v13/*.svg` means the
vector data in the TypeScript is byte-identical to the exported original, and re-running this
script proves it: if the output differs from what is committed, someone edited the derived file.

## Why the XML is inlined rather than imported

`react-native-svg` can render an SVG file only through a Metro transformer, which this project does
not install. `SvgXml` takes the markup as a string instead, so the markup has to reach the bundle
as source. The `.svg` files remain the committed originals and this module is their derivative;
neither is authored by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

#: Each committed export directory and the module generated from it.
#:
#: V14 was added because `info-back.svg` was imported through `require()` and handed to an
#: `<Image>`, which on Android renders nothing at all — the rule sheets drew no back chevron. There
#: is no SVG Metro transformer here, so an `.svg` can only reach the bundle as inlined source.
REVISIONS = [
    ("figma-v13", "figmaV13Icons.ts", "V13"),
    ("figma-v14", "figmaV14Icons.ts", "V14"),
]


def camel(stem: str) -> str:
    head, *rest = stem.split("-")
    return head + "".join(part.capitalize() for part in rest)


def generate(directory: str, module: str, label: str) -> int:
    svg_dir = ROOT / "assets" / "images" / directory
    out = ROOT / "src" / "ui" / "icons" / module
    svgs = sorted(svg_dir.glob("*.svg"))
    ledger_path = svg_dir / "ASSETS.json"
    ledger = (
        json.loads(ledger_path.read_text(encoding="utf-8"))["assets"]
        if ledger_path.exists()
        else {}
    )

    lines = [
        "/**",
        f" * Figma {label} vector icons, inlined verbatim from the committed exports.",
        " *",
        " * GENERATED by `python scripts/visual/build_icons.py` — do not edit by hand. Each string",
        f" * is the exact content of the matching file in `assets/images/{directory}/`, which is the",
        " * original Figma export; re-running the generator must produce no diff.",
        " *",
        " * Render with `SvgXml` from `react-native-svg`. The project has no SVG Metro transformer,",
        " * so the markup has to reach the bundle as source rather than as an import — handing the",
        " * `.svg` to an `<Image>` renders nothing on Android.",
        " */",
        "",
    ]
    for path in svgs:
        name = camel(path.stem)
        entry = ledger.get(path.name, {})
        nodes = ", ".join(entry.get("nodes", []))
        markup = path.read_text(encoding="utf-8").strip()
        lines.append(f"/** `{path.name}` — Figma nodes: {nodes}. */")
        lines.append(f"export const {name} = {json.dumps(markup)};")
        lines.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(svgs)} icons)")
    return len(svgs)


def main() -> int:
    for directory, module, label in REVISIONS:
        generate(directory, module, label)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
