"""
Generate `src/ui/icons/figmaV13Icons.ts` from the committed Figma V13 SVG exports.

## Why generate instead of hand-writing

The brief forbids invented SVGs, and hand-transcribing a path is exactly that — a redrawing that
happens to look similar. Generating the module from `assets/images/figma-v13/*.svg` means the
vector data in the TypeScript is byte-identical to the exported original, and re-running this
script proves it: if the output differs from what is committed, someone edited the derived file.

## Why the XML is inlined rather than imported

`react-native-svg` can render an SVG file only through a Metro transformer, which this project does
not install. `SvgXml` takes the markup as a string instead, so the markup has to reach the bundle
as source. The `.svg` files remain the committed originals and this module is their derivative;
neither is authored by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SVG_DIR = ROOT / "assets" / "images" / "figma-v13"
OUT = ROOT / "src" / "ui" / "icons" / "figmaV13Icons.ts"


def camel(stem: str) -> str:
    head, *rest = stem.split("-")
    return head + "".join(part.capitalize() for part in rest)


def main() -> int:
    svgs = sorted(SVG_DIR.glob("*.svg"))
    ledger = json.loads((SVG_DIR / "ASSETS.json").read_text(encoding="utf-8"))["assets"]

    lines = [
        "/**",
        " * Figma V13 vector icons, inlined verbatim from the committed exports.",
        " *",
        " * GENERATED by `python scripts/visual/build_icons.py` — do not edit by hand. Each string",
        " * is the exact content of the matching file in `assets/images/figma-v13/`, which is the",
        " * original Figma export; re-running the generator must produce no diff.",
        " *",
        " * Render with `SvgXml` from `react-native-svg`. The project has no SVG Metro transformer,",
        " * so the markup has to reach the bundle as source rather than as an import.",
        " */",
        "",
    ]
    for path in svgs:
        name = camel(path.stem)
        entry = ledger.get(path.name, {})
        nodes = ", ".join(entry.get("nodes", []))
        markup = path.read_text(encoding="utf-8").strip()
        lines.append(f"/** `{path.name}` — Figma nodes: {nodes}. */")
        lines.append(f"export const {name} = {json.dumps(markup)};")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(svgs)} icons)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
