"""
Render the V13 pixel-verification manifest from evidence on disk.

The manifest is derived, never hand-maintained: every column is read back from an artefact that
had to exist for the work to have happened, so a row cannot claim progress that left no trace.

| column            | source of truth                                                          |
| ----------------- | ------------------------------------------------------------------------ |
| Context captured  | `scripts/visual/context-captured.json` — written per `get_design_context` |
| Assets downloaded | `assets/images/figma-v13/ASSETS.json` — node ids recorded per asset       |
| Implemented       | a gallery state exists AND that screen's V13 context was captured         |
| Emulator compared | `docs/visual-verification/v13/<section>/<node>/result.json` exists        |
| Result            | `verdicts.json` verdict, plus the measured `differingPixelPercent`        |

"Implemented" deliberately requires **both** a gallery entry and a captured design context. Twelve
Service-flow screens carry a gallery entry inherited from V12; they render, but they were never
built against a V13 `get_design_context` and every one of them fails its frame. Counting those as
implemented would overstate progress by a third of the inventory, so they are reported as
`carried-over` instead.

`verdicts.json` is the one human-entered file. The comparison script deliberately writes
`PENDING_REVIEW` and never decides PASS itself, because a low percentage is not the same as a
correct screen — a blank render against a mostly-white frame scores well. A verdict is recorded
only after the overlay and diff have actually been read.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EVIDENCE = ROOT / "docs" / "visual-verification" / "v13"
ASSET_LEDGER = ROOT / "assets" / "images" / "figma-v13" / "ASSETS.json"
CONTEXT_LEDGER = Path(__file__).resolve().parent / "context-captured.json"
GALLERY_STATES = Path(__file__).resolve().parent / "gallery-states.json"
VERDICTS = EVIDENCE / "verdicts.json"

SECTION_SLUGS = {
    "Login flow": "login-flow",
    "leave": "leave",
    "log in flow": "log-in-flow",
    "performance": "performance",
    "Service flow": "service-flow",
}

#: Implementation order fixed by the brief.
SECTION_ORDER = ["Login flow", "log in flow", "leave", "performance", "Service flow"]


def load_json(path: Path, default):
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return default


def build_rows() -> list[dict]:
    inventory = load_json(EVIDENCE / "inventory.json", [])
    contexts = set(load_json(CONTEXT_LEDGER, {}).get("nodes", []))
    assets = load_json(ASSET_LEDGER, {"assets": {}})["assets"]
    states = load_json(GALLERY_STATES, {})
    verdicts = load_json(VERDICTS, {})

    nodes_with_assets: dict[str, list[str]] = {}
    for filename, entry in assets.items():
        for node in entry["nodes"]:
            nodes_with_assets.setdefault(node, []).append(filename)

    state_by_node = {node: state for state, node in states.items()}

    rows = []
    for row in inventory:
        node = row["nodeId"]
        slug = SECTION_SLUGS[row["section"]]
        out_dir = EVIDENCE / slug / node.replace(":", "-")
        result = load_json(out_dir / "result.json", None)
        rows.append(
            {
                "nodeId": node,
                "section": row["section"],
                "name": row["name"],
                "context": node in contexts,
                "assets": nodes_with_assets.get(node, []),
                "galleryState": state_by_node.get(node),
                "v13Implemented": state_by_node.get(node) is not None and node in contexts,
                "compared": result is not None,
                "diff": result["differingPixelPercent"] if result else None,
                "raw": result["rawDifferingPixelPercent"] if result else None,
                "verdict": verdicts.get(node, "—"),
            }
        )
    rows.sort(key=lambda r: (SECTION_ORDER.index(r["section"]), r["nodeId"]))
    return rows


def render(rows: list[dict]) -> str:
    def tick(value: bool) -> str:
        return "yes" if value else "—"

    lines = [
        "# V13 pixel-verification manifest",
        "",
        "Generated by `python scripts/visual/manifest.py --write`. Every column is read back from",
        "an artefact on disk; nothing here is asserted by hand except the reviewed verdict.",
        "",
        "| Node ID | Section | Screen | Context captured | Assets downloaded | Implemented | Emulator compared | diff % | Result |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        assets = f"{len(r['assets'])}" if r["assets"] else "—"
        if r["v13Implemented"]:
            implemented = f"`{r['galleryState']}`"
        elif r["galleryState"]:
            implemented = f"carried-over (`{r['galleryState']}`)"
        else:
            implemented = "—"
        diff = f"{r['diff']:.2f}" if r["diff"] is not None else "—"
        lines.append(
            f"| `{r['nodeId']}` | {r['section']} | {r['name']} | {tick(r['context'])} | "
            f"{assets} | {implemented} | {tick(r['compared'])} | {diff} | {r['verdict']} |"
        )

    passing = sum(1 for r in rows if r["verdict"] == "PASS")
    lines += [
        "",
        "## Totals",
        "",
        f"- FINAL_SECTION_SCREEN_COUNT: {len(rows)}",
        f"- CONTEXT_CAPTURED: {sum(1 for r in rows if r['context'])}",
        f"- SCREENS_IMPLEMENTED: {sum(1 for r in rows if r['v13Implemented'])}",
        f"- SCREENS_CARRIED_OVER_FROM_V12: "
        f"{sum(1 for r in rows if r['galleryState'] and not r['v13Implemented'])}",
        f"- SCREENS_EMULATOR_RENDERED: {sum(1 for r in rows if r['compared'])}",
        f"- SCREENS_PIXEL_VERIFIED: {passing}",
        f"- SCREENS_STILL_MISMATCHING: {len(rows) - passing}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write MANIFEST.md")
    parser.add_argument("--record-context", nargs="*", default=None, help="Node ids to mark captured")
    parser.add_argument("--verdict", nargs=2, default=None, metavar=("NODE", "VERDICT"))
    args = parser.parse_args()

    if args.record_context:
        ledger = load_json(CONTEXT_LEDGER, {"nodes": []})
        for node in args.record_context:
            if node not in ledger["nodes"]:
                ledger["nodes"].append(node)
        ledger["nodes"].sort()
        CONTEXT_LEDGER.write_text(json.dumps(ledger, indent=1) + "\n", encoding="utf-8")
        print(f"context ledger: {len(ledger['nodes'])} nodes")

    if args.verdict:
        node, verdict = args.verdict
        verdicts = load_json(VERDICTS, {})
        verdicts[node] = verdict
        VERDICTS.write_text(
            json.dumps(dict(sorted(verdicts.items())), indent=1) + "\n", encoding="utf-8"
        )
        print(f"verdict: {node} = {verdict}")

    rows = build_rows()
    text = render(rows)
    if args.write:
        (EVIDENCE / "MANIFEST.md").write_text(text, encoding="utf-8")
        print(f"wrote {EVIDENCE / 'MANIFEST.md'}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
