/**
 * Typed Cook endpoints.
 *
 * One function per backend route, named for what the cook is doing. Every one of these was
 * verified as REGISTERED in `src/api/routes/v1/index.ts` — not merely present in `openapi.yaml`,
 * which declares a generic `Ok` response for all of them and therefore proves nothing about the
 * body.
 *
 * Idempotency: the backend REQUIRES an `Idempotency-Key` header on the mutating cook commands and
 * rejects the call with `INVALID_REQUEST` without one. The key is generated by the CALLER and must
 * stay stable across user-initiated retries of the same intent, so a double-tap cannot produce two
 * check-ins. `newIdempotencyKey()` is therefore called once per intent, not once per attempt.
 */

import { request, type RequestOptions } from './client';
import {
  authSessionSchema,
  commandAckSchema,
  cookCyclesSchema,
  cookEarningsSchema,
  cookJobSchema,
  cookAttendanceRangeSchema,
  cookCycleDetailSchema,
  cookJobsListSchema,
  cookLeaveRequestSchema,
  cookLeavesSchema,
  cookLocationSchema,
  cookPresentSchema,
  cookProfileSchema,
  currentCookJobSchema,
  monthlyAttendanceSchema,
  otpSendSchema,
  type AuthSessionResponse,
  type CookCyclesResponse,
  type CookEarningsResponse,
  type CookJobResponse,
  type CookAttendanceRangeResponse,
  type CookCycleDetailResponse,
  type CookJobsListResponse,
  type CookLeaveRequestResponse,
  type CookLeavesResponse,
  type CookLocationResponse,
  type CookPresentResponse,
  type CookProfileResponse,
  type MonthlyAttendanceResponse,
} from './schemas';

/** A per-intent idempotency key. Not a nonce — reuse it for retries of the SAME intent. */
export function newIdempotencyKey(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 12)}`;
}

type Opts = Pick<RequestOptions, 'signal'>;

/* ----------------------------------------------------------------- auth --- */

/**
 * Request a login OTP.
 *
 * `audience: 'cook'` is essential. Without it the backend takes the customer branch, which
 * auto-provisions an unknown phone as an active customer.
 */
export async function requestLoginOtp(phoneE164: string, opts: Opts = {}): Promise<void> {
  await request('/auth/otp/send', otpSendSchema, {
    method: 'POST',
    body: { phone: phoneE164, audience: 'cook' },
    anonymous: true,
    ...opts,
  });
}

/**
 * Verify a login OTP and open a session.
 *
 * Cook-audience failures are deliberately coarse on the server side:
 *   `400 INVALID_REQUEST`  → wrong or expired OTP
 *   `401 UNAUTHENTICATED`  → this phone is not a provisioned cook
 *   `403 FORBIDDEN`        → a cook exists but is not active/approved
 * The server will not say which of "unknown" or "not eligible" applies, so the app must not
 * invent a more specific explanation than it was given.
 */
export async function verifyLoginOtp(
  input: { readonly phoneE164: string; readonly otp: string; readonly deviceId: string },
  opts: Opts = {},
): Promise<AuthSessionResponse> {
  return request('/auth/otp/verify', authSessionSchema, {
    method: 'POST',
    body: {
      phone: input.phoneE164,
      otp: input.otp,
      deviceId: input.deviceId,
      audience: 'cook',
    },
    anonymous: true,
    ...opts,
  });
}

export async function logout(opts: Opts = {}): Promise<void> {
  await request('/auth/logout', commandAckSchema, { method: 'POST', ...opts });
}

/* ------------------------------------------------------------- identity --- */

/** The cook's operational profile: identity, hub, rating, today's shift, attendance, assignment. */
export async function getCookProfile(opts: Opts = {}): Promise<CookProfileResponse> {
  return request('/cook/me', cookProfileSchema, opts);
}

/* ----------------------------------------------------------------- jobs --- */

export async function listJobs(
  params: { readonly from?: string; readonly to?: string; readonly limit?: number } = {},
  opts: Opts = {},
): Promise<CookJobsListResponse> {
  return request('/cook/jobs', cookJobsListSchema, {
    query: {
      ...(params.from === undefined ? {} : { from: params.from }),
      ...(params.to === undefined ? {} : { to: params.to }),
      ...(params.limit === undefined ? {} : { limit: params.limit }),
    },
    ...opts,
  });
}

/**
 * The active assignment, reconstructed from the database.
 *
 * This is what makes restart recovery correct: the app never restores a service screen from local
 * state, it re-reads the projection and renders whatever the server says is true now.
 */
export async function getCurrentJob(opts: Opts = {}): Promise<CookJobResponse | null> {
  return request('/cook/jobs/current', currentCookJobSchema, opts);
}

export async function getJob(bookingId: string, opts: Opts = {}): Promise<CookJobResponse> {
  return request(`/cook/jobs/${bookingId}`, cookJobSchema, opts);
}

/* --------------------------------------------------------- service flow --- */

/**
 * The GO command — begins the COMMUTE, not the service.
 *
 * `assignmentVersion` is sent so a cook acting on a screen that predates a reassignment is
 * refused with `ACTIVE_ASSIGNMENT_CHANGED` instead of starting travel to a job that is no longer
 * theirs.
 */
export async function startCommute(
  input: {
    readonly bookingId: string;
    readonly assignmentVersion: number;
    readonly idempotencyKey: string;
  },
  opts: Opts = {},
): Promise<void> {
  await request(`/cook/bookings/${input.bookingId}/start-commute`, commandAckSchema, {
    method: 'POST',
    body: { assignmentVersion: input.assignmentVersion },
    idempotencyKey: input.idempotencyKey,
    ...opts,
  });
}

/**
 * Fallback arrival command.
 *
 * Arrival is normally committed by the backend from accepted GPS samples. This exists for a device
 * whose background location was throttled. It is NOT independent authority: with no recent
 * in-radius sample the backend answers `409 ARRIVAL_PROXIMITY_NOT_CONFIRMED` and changes nothing.
 */
export async function markArrived(
  input: {
    readonly bookingId: string;
    readonly assignmentVersion: number;
    readonly idempotencyKey: string;
  },
  opts: Opts = {},
): Promise<void> {
  await request(`/cook/bookings/${input.bookingId}/arrive`, commandAckSchema, {
    method: 'POST',
    body: { assignmentVersion: input.assignmentVersion },
    idempotencyKey: input.idempotencyKey,
    ...opts,
  });
}

/** Verify the 3-digit Start OTP the customer reads out. Moves the booking to `cooking`. */
export async function verifyStartOtp(
  input: {
    readonly bookingId: string;
    readonly otp: string;
    readonly assignmentVersion: number;
    readonly idempotencyKey: string;
  },
  opts: Opts = {},
): Promise<void> {
  await request(`/cook/bookings/${input.bookingId}/verify-start-otp`, commandAckSchema, {
    method: 'POST',
    body: { otp: input.otp, assignmentVersion: input.assignmentVersion },
    idempotencyKey: input.idempotencyKey,
    ...opts,
  });
}

/** Verify the 3-digit End OTP. Completes the booking. A timer reaching zero never completes one. */
export async function verifyEndOtp(
  input: {
    readonly bookingId: string;
    readonly otp: string;
    readonly assignmentVersion: number;
    readonly idempotencyKey: string;
  },
  opts: Opts = {},
): Promise<void> {
  await request(`/cook/bookings/${input.bookingId}/verify-end-otp`, commandAckSchema, {
    method: 'POST',
    body: { otp: input.otp, assignmentVersion: input.assignmentVersion },
    idempotencyKey: input.idempotencyKey,
    ...opts,
  });
}

/**
 * Report one GPS sample during travel.
 *
 * Answers `202` whether or not the sample was accepted — an unreliable reading must never become
 * a finding against the cook. When `arrived` comes back true the backend has committed the
 * transition and the client should stop reporting.
 */
export async function reportLocation(
  input: {
    readonly bookingId: string;
    readonly assignmentVersion: number;
    readonly latitude: number;
    readonly longitude: number;
    readonly accuracyMetres: number;
    readonly recordedAtIso: string;
    readonly mocked?: boolean;
  },
  opts: Opts = {},
): Promise<CookLocationResponse> {
  return request('/cook/location', cookLocationSchema, {
    method: 'POST',
    body: {
      bookingId: input.bookingId,
      assignmentVersion: input.assignmentVersion,
      latitude: input.latitude,
      longitude: input.longitude,
      // The route schema is `additionalProperties: false` and names this field `accuracyMeters`.
      // An earlier build sent `accuracy`, which the deployed API rejects with 400 INVALID_REQUEST
      // before the handler runs — every sample would have been dropped at the edge.
      accuracyMeters: input.accuracyMetres,
      recordedAt: input.recordedAtIso,
      ...(input.mocked === undefined ? {} : { mocked: input.mocked }),
    },
    ...opts,
  });
}

/**
 * Responsiveness evidence only. Changes no booking state and never marks the cook safe.
 *
 * `assignmentVersion` is OPTIONAL, and omitted rather than defaulted when the caller does not have
 * one. The route schema declares `{ type: 'integer', minimum: 1 }`, so a placeholder `0` is
 * rejected as `400 INVALID_REQUEST` by Fastify before the handler runs — every acknowledgement
 * sent from a context without a loaded projection (a notification tap, for instance) would fail.
 * Omitting the field lets the backend fence on the current assignment itself.
 */
export async function acknowledgeAlert(
  input: {
    readonly bookingId: string;
    readonly alertType: 'start_alert' | 'start_escalation' | 'move_alert';
    readonly assignmentVersion?: number | undefined;
  },
  opts: Opts = {},
): Promise<void> {
  await request(`/cook/bookings/${input.bookingId}/acknowledge-alert`, commandAckSchema, {
    method: 'POST',
    body: {
      alertType: input.alertType,
      ...(input.assignmentVersion === undefined || input.assignmentVersion < 1
        ? {}
        : { assignmentVersion: input.assignmentVersion }),
    },
    ...opts,
  });
}

/* ----------------------------------------------------------- attendance --- */

/**
 * Cook-initiated check-in.
 *
 * The server owns the service date, the check-in timestamp and the on-time ruling. A replay
 * returns the ORIGINAL result with `created: false` — that is the "already present" response, and
 * it is a success, not an error.
 *
 * Rejections that are not failures of the app:
 *   `400` — no shift today, an approved leave today, or an existing non-present record
 *   `403` — the cook is not active
 */
export async function markPresent(
  idempotencyKey: string,
  opts: Opts = {},
): Promise<CookPresentResponse> {
  return request('/cook/attendance/present', cookPresentSchema, {
    method: 'POST',
    body: {},
    idempotencyKey,
    ...opts,
  });
}

/**
 * Month-scoped attendance.
 *
 * `scheduled` comes from `cook_shifts` and is returned SEPARATELY from `status`, so the app can
 * render the `Scheduled` legend entry without ever writing `scheduled` as an attendance status.
 * `onTimePercentage` is server-computed and is `null` when the month has no present days.
 */
export async function getMonthlyAttendance(
  month: string,
  opts: Opts = {},
): Promise<MonthlyAttendanceResponse> {
  return request('/cook/attendance/month', monthlyAttendanceSchema, {
    query: { month },
    ...opts,
  });
}

/**
 * Stored attendance records inside a window.
 *
 * Used by the cycle frame's Mon–Sun strip. A date absent from the response has NO record and is
 * rendered blank — inferring `absent` from absence would accuse a cook the server never marked.
 */
export async function listAttendanceRange(
  params: { readonly from: string; readonly to: string },
  opts: Opts = {},
): Promise<CookAttendanceRangeResponse> {
  return request('/cook/attendance', cookAttendanceRangeSchema, {
    query: { from: params.from, to: params.to },
    ...opts,
  });
}

/** Leave requests overlapping a window, grouped by request. Includes pending and rejected. */
export async function listLeaves(
  params: { readonly from?: string; readonly to?: string } = {},
  opts: Opts = {},
): Promise<CookLeavesResponse> {
  return request('/cook/leaves', cookLeavesSchema, {
    query: {
      ...(params.from === undefined ? {} : { from: params.from }),
      ...(params.to === undefined ? {} : { to: params.to }),
    },
    ...opts,
  });
}

/**
 * Submit a cook-initiated leave request.
 *
 * Deployed and verified: `POST /v1/cook/leaves` is registered on the live API. It answers `201`
 * with `status: 'pending'` — Ops/Admin still decide. The app must never render the leave as taken.
 *
 * Backend rejections that are not app failures:
 *   `400` — `startDate` in the past, or `endDate` before `startDate`
 *   `409` — an overlapping pending/approved leave already exists (`INVALID_BOOKING_STATE`)
 *   `403` — the cook is not active
 */
export async function requestLeave(
  input: {
    readonly startDateIso: string;
    readonly endDateIso: string;
    readonly reason?: string;
    readonly idempotencyKey: string;
  },
  opts: Opts = {},
): Promise<CookLeaveRequestResponse> {
  return request('/cook/leaves', cookLeaveRequestSchema, {
    method: 'POST',
    body: {
      startDate: input.startDateIso,
      endDate: input.endDateIso,
      ...(input.reason === undefined || input.reason.length === 0 ? {} : { reason: input.reason }),
    },
    idempotencyKey: input.idempotencyKey,
    ...opts,
  });
}

/* ------------------------------------------------------------- earnings --- */

/**
 * Daily, seven-day and current-cycle earnings plus bonus progress.
 *
 * Every figure is a server projection. The app formats paise and does no arithmetic — and the
 * bonus threshold arrives as `bonus.thresholdDays`, so no screen hardcodes 5, 7 or 27.
 */
export async function getEarnings(
  params: { readonly limit?: number } = {},
  opts: Opts = {},
): Promise<CookEarningsResponse> {
  return request('/cook/earnings', cookEarningsSchema, {
    query: { ...(params.limit === undefined ? {} : { limit: params.limit }) },
    ...opts,
  });
}

export async function listEarningsCycles(
  params: { readonly limit?: number } = {},
  opts: Opts = {},
): Promise<CookCyclesResponse> {
  return request('/cook/earnings/cycles', cookCyclesSchema, {
    query: { ...(params.limit === undefined ? {} : { limit: params.limit }) },
    ...opts,
  });
}

/**
 * One past cycle.
 *
 * Deliberately NOT `cookEarningsSchema`: `getCookCycle` answers with `{ cycleId, startDate,
 * endDate, status, breakdown, summary, totalPaise, events }`. Validating it against the
 * `/cook/earnings` schema — as an earlier build did — fails on every response.
 */
export async function getEarningsCycle(
  cycleId: string,
  opts: Opts = {},
): Promise<CookCycleDetailResponse> {
  return request(`/cook/earnings/cycles/${cycleId}`, cookCycleDetailSchema, opts);
}

/* -------------------------------------------------------------- devices --- */

/** Register this device for push. The token is a secret and is never logged or echoed. */
export async function registerPushToken(
  input: { readonly token: string; readonly platform: 'android' | 'ios' },
  opts: Opts = {},
): Promise<void> {
  await request('/me/push-token', commandAckSchema, {
    method: 'PUT',
    body: { token: input.token, platform: input.platform },
    ...opts,
  });
}
