/**
 * Typed Cook endpoints.
 *
 * One function per backend route, named for what the cook is doing. Every one of these was
 * verified as REGISTERED in `src/api/routes/v1/index.ts` — not merely present in `openapi.yaml`,
 * which declares a generic `Ok` response for all of them and therefore proves nothing about the
 * body.
 *
 * Idempotency: the backend REQUIRES an `Idempotency-Key` header on the mutating cook commands and
 * rejects the call with `INVALID_REQUEST` without one. The key is generated by the CALLER and must
 * stay stable across user-initiated retries of the same intent, so a double-tap cannot produce two
 * check-ins. `newIdempotencyKey()` is therefore called once per intent, not once per attempt.
 */

import { request, type RequestOptions } from './client';
import {
  cookEarningsPolicySchema,
  type CookEarningsPolicy,
  authSessionSchema,
  commandAckSchema,
  cookCyclesSchema,
  cookWeeksSchema,
  cookWeekDetailSchema,
  cookEarningsSchema,
  cookJobSchema,
  cookAttendanceRangeSchema,
  cookCycleDetailSchema,
  cookJobsListSchema,
  cookLeaveRequestSchema,
  cookLeavesSchema,
  cookLocationSchema,
  cookPresenceLocationSchema,
  cookPresentSchema,
  cookProfileSchema,
  currentCookJobSchema,
  earningsPeriodSchema,
  monthlyAttendanceSchema,
  otpSendSchema,
  type AuthSessionResponse,
  type CookEarningsPeriodResponse,
  type CookCyclesResponse,
  type CookWeeksResponse,
  type CookWeekDetailResponse,
  type CookEarningsResponse,
  type CookJobResponse,
  type CookAttendanceRangeResponse,
  type CookCycleDetailResponse,
  type CookJobsListResponse,
  type CookLeaveRequestResponse,
  type CookLeavesResponse,
  type CookLocationResponse,
  type CookPresentResponse,
  type CookProfileResponse,
  type MonthlyAttendanceResponse,
} from './schemas';

/** A per-intent idempotency key. Not a nonce — reuse it for retries of the SAME intent. */
export function newIdempotencyKey(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 12)}`;
}

type Opts = Pick<RequestOptions, 'signal'>;

/* ----------------------------------------------------------------- auth --- */

/**
 * Request a login OTP.
 *
 * `audience: 'cook'` is essential. Without it the backend takes the customer branch, which
 * auto-provisions an unknown phone as an active customer.
 */
export async function requestLoginOtp(phoneE164: string, opts: Opts = {}): Promise<void> {
  await request('/auth/otp/send', otpSendSchema, {
    method: 'POST',
    body: { phone: phoneE164, audience: 'cook' },
    anonymous: true,
    ...opts,
  });
}

/**
 * Verify a login OTP and open a session.
 *
 * Cook-audience failures are deliberately coarse on the server side:
 *   `400 INVALID_REQUEST`  → wrong or expired OTP
 *   `401 UNAUTHENTICATED`  → this phone is not a provisioned cook
 *   `403 FORBIDDEN`        → a cook exists but is not active/approved
 * The server will not say which of "unknown" or "not eligible" applies, so the app must not
 * invent a more specific explanation than it was given.
 */
export async function verifyLoginOtp(
  input: { readonly phoneE164: string; readonly otp: string; readonly deviceId: string },
  opts: Opts = {},
): Promise<AuthSessionResponse> {
  return request('/auth/otp/verify', authSessionSchema, {
    method: 'POST',
    body: {
      phone: input.phoneE164,
      otp: input.otp,
      deviceId: input.deviceId,
      audience: 'cook',
    },
    anonymous: true,
    ...opts,
  });
}

export async function logout(opts: Opts = {}): Promise<void> {
  await request('/auth/logout', commandAckSchema, { method: 'POST', ...opts });
}

/* ------------------------------------------------------------- identity --- */

/** The cook's operational profile: identity, hub, rating, today's shift, attendance, assignment. */
export async function getCookProfile(opts: Opts = {}): Promise<CookProfileResponse> {
  return request('/cook/me', cookProfileSchema, opts);
}

/* --------------------------------------------------------------- policy --- */

/**
 * The active published earnings policy.
 *
 * Read once per session and cached: it changes when an owner publishes, not per request. The
 * server sends an ETag and a five-minute `max-age`, so a publication reaches a running app
 * without a release and without polling it hard.
 */
export async function getEarningsPolicy(opts: Opts = {}): Promise<CookEarningsPolicy> {
  return request('/cook/policies/earnings', cookEarningsPolicySchema, opts);
}

/* ----------------------------------------------------------------- jobs --- */

export async function listJobs(
  params: { readonly from?: string; readonly to?: string; readonly limit?: number } = {},
  opts: Opts = {},
): Promise<CookJobsListResponse> {
  return request('/cook/jobs', cookJobsListSchema, {
    query: {
      ...(params.from === undefined ? {} : { from: params.from }),
      ...(params.to === undefined ? {} : { to: params.to }),
      ...(params.limit === undefined ? {} : { limit: params.limit }),
    },
    ...opts,
  });
}

/**
 * The active assignment, reconstructed from the database.
 *
 * This is what makes restart recovery correct: the app never restores a service screen from local
 * state, it re-reads the projection and renders whatever the server says is true now.
 */
export async function getCurrentJob(opts: Opts = {}): Promise<CookJobResponse | null> {
  return request('/cook/jobs/current', currentCookJobSchema, opts);
}

export async function getJob(bookingId: string, opts: Opts = {}): Promise<CookJobResponse> {
  return request(`/cook/jobs/${bookingId}`, cookJobSchema, opts);
}

/* --------------------------------------------------------- service flow --- */

/**
 * The GO command — begins the COMMUTE, not the service.
 *
 * `assignmentVersion` is sent so a cook acting on a screen that predates a reassignment is
 * refused with `ACTIVE_ASSIGNMENT_CHANGED` instead of starting travel to a job that is no longer
 * theirs.
 */
export async function startCommute(
  input: {
    readonly bookingId: string;
    readonly assignmentVersion: number;
    readonly idempotencyKey: string;
  },
  opts: Opts = {},
): Promise<void> {
  await request(`/cook/bookings/${input.bookingId}/start-commute`, commandAckSchema, {
    method: 'POST',
    body: { assignmentVersion: input.assignmentVersion },
    idempotencyKey: input.idempotencyKey,
    ...opts,
  });
}

/**
 * Fallback arrival command.
 *
 * Arrival is normally committed by the backend from accepted GPS samples. This exists for a device
 * whose background location was throttled. It is NOT independent authority: with no recent
 * in-radius sample the backend answers `409 ARRIVAL_PROXIMITY_NOT_CONFIRMED` and changes nothing.
 */
export async function markArrived(
  input: {
    readonly bookingId: string;
    readonly assignmentVersion: number;
    readonly idempotencyKey: string;
  },
  opts: Opts = {},
): Promise<void> {
  await request(`/cook/bookings/${input.bookingId}/arrive`, commandAckSchema, {
    method: 'POST',
    body: { assignmentVersion: input.assignmentVersion },
    idempotencyKey: input.idempotencyKey,
    ...opts,
  });
}

/** Verify the 3-digit Start OTP the customer reads out. Moves the booking to `cooking`. */
export async function verifyStartOtp(
  input: {
    readonly bookingId: string;
    readonly otp: string;
    readonly assignmentVersion: number;
    readonly idempotencyKey: string;
  },
  opts: Opts = {},
): Promise<void> {
  await request(`/cook/bookings/${input.bookingId}/verify-start-otp`, commandAckSchema, {
    method: 'POST',
    body: { otp: input.otp, assignmentVersion: input.assignmentVersion },
    idempotencyKey: input.idempotencyKey,
    ...opts,
  });
}

/** Verify the 3-digit End OTP. Completes the booking. A timer reaching zero never completes one. */
export async function verifyEndOtp(
  input: {
    readonly bookingId: string;
    readonly otp: string;
    readonly assignmentVersion: number;
    readonly idempotencyKey: string;
  },
  opts: Opts = {},
): Promise<void> {
  await request(`/cook/bookings/${input.bookingId}/verify-end-otp`, commandAckSchema, {
    method: 'POST',
    body: { otp: input.otp, assignmentVersion: input.assignmentVersion },
    idempotencyKey: input.idempotencyKey,
    ...opts,
  });
}

/**
 * Report one GPS sample during travel.
 *
 * Answers `202` whether or not the sample was accepted — an unreliable reading must never become
 * a finding against the cook. When `arrived` comes back true the backend has committed the
 * transition and the client should stop reporting.
 */
/**
 * Reports where the cook is while she is NOT on a job.
 *
 * `reportLocation` is the evidence stream and needs a booking and an assignment version; between
 * jobs there is neither. Instant availability routes from the cook's current position, and the
 * background stream only runs during travel — so once she arrives, her fix ages out and an idle,
 * present, perfectly bookable cook has no origin for the engine to route from. This is the ping
 * that keeps her reachable.
 *
 * Fire-and-forget by contract: the API answers 202 with nothing worth reading, and a failure here
 * must never surface to a cook who is not doing anything wrong.
 */
export async function reportPresenceLocation(
  input: {
    readonly latitude: number;
    readonly longitude: number;
    readonly accuracyMetres: number;
    readonly recordedAtIso: string;
  },
  opts: Opts = {},
): Promise<void> {
  await request('/cook/presence-location', cookPresenceLocationSchema, {
    method: 'POST',
    body: {
      latitude: input.latitude,
      longitude: input.longitude,
      // Named `accuracyMeters` by the route schema, which is `additionalProperties: false`.
      accuracyMeters: input.accuracyMetres,
      recordedAt: input.recordedAtIso,
    },
    ...opts,
  });
}

export async function reportLocation(
  input: {
    readonly bookingId: string;
    readonly assignmentVersion: number;
    readonly latitude: number;
    readonly longitude: number;
    readonly accuracyMetres: number;
    readonly recordedAtIso: string;
    readonly mocked?: boolean;
  },
  opts: Opts = {},
): Promise<CookLocationResponse> {
  return request('/cook/location', cookLocationSchema, {
    method: 'POST',
    body: {
      bookingId: input.bookingId,
      assignmentVersion: input.assignmentVersion,
      latitude: input.latitude,
      longitude: input.longitude,
      // The route schema is `additionalProperties: false` and names this field `accuracyMeters`.
      // An earlier build sent `accuracy`, which the deployed API rejects with 400 INVALID_REQUEST
      // before the handler runs — every sample would have been dropped at the edge.
      accuracyMeters: input.accuracyMetres,
      recordedAt: input.recordedAtIso,
      ...(input.mocked === undefined ? {} : { mocked: input.mocked }),
    },
    ...opts,
  });
}

/**
 * Responsiveness evidence only. Changes no booking state and never marks the cook safe.
 *
 * `assignmentVersion` is OPTIONAL, and omitted rather than defaulted when the caller does not have
 * one. The route schema declares `{ type: 'integer', minimum: 1 }`, so a placeholder `0` is
 * rejected as `400 INVALID_REQUEST` by Fastify before the handler runs — every acknowledgement
 * sent from a context without a loaded projection (a notification tap, for instance) would fail.
 * Omitting the field lets the backend fence on the current assignment itself.
 *
 * ## Every acknowledgement this app ever sent was rejected
 *
 * This call sent no `Idempotency-Key`, and the route rejects a request without one before the
 * handler runs:
 *
 *     const idempotencyKey = request.headers['idempotency-key'];
 *     if (typeof idempotencyKey !== 'string') throw new AppError(errorCodes.INVALID_REQUEST);
 *
 * So the header was missing, the call 400'd, and both call sites — the notification tap and the
 * in-app command — discarded the failure. `start_alerts.acknowledged_at` could therefore never
 * be set by this app, which is why the 2026-08-30 audit found no acknowledgements anywhere.
 *
 * That is not a cosmetic loss. Acknowledgement is one of the two proofs that word reached the
 * cook, and the elapsed-window sweep now charges a no-show penalty only when it did. A cook who
 * tapped the alert had no record of tapping it.
 *
 * ## Why the key is derived here rather than passed in
 *
 * Every other command in this file takes the key from the caller, because their intents are
 * things a cook chooses to do twice — two check-ins, two leave requests — and only the caller
 * can say whether a second tap is a retry or a new intent. An acknowledgement is not like that:
 * it has ONE natural identity, the alert being acknowledged, and acknowledging the same alert
 * twice is the same fact stated twice. Deriving it here also means the background notification
 * handler — which has no React state to hold a key in, and where the same notification really can
 * be tapped twice — gets a stable key for free rather than a fresh one per tap.
 *
 * The version is part of the key when known, because a reassignment produces a genuinely
 * different alert (`start_alerts` is `UNIQUE (assignment_id, kind)`) and its acknowledgement must
 * not be swallowed as a replay of the previous cook's.
 */
export async function acknowledgeAlert(
  input: {
    readonly bookingId: string;
    readonly alertType: 'start_alert' | 'start_escalation' | 'move_alert';
    readonly assignmentVersion?: number | undefined;
  },
  opts: Opts = {},
): Promise<void> {
  const version =
    input.assignmentVersion === undefined || input.assignmentVersion < 1
      ? undefined
      : input.assignmentVersion;
  await request(`/cook/bookings/${input.bookingId}/acknowledge-alert`, commandAckSchema, {
    method: 'POST',
    idempotencyKey: `ack-${input.bookingId}-${input.alertType}${version === undefined ? '' : `-v${String(version)}`}`,
    body: {
      alertType: input.alertType,
      ...(version === undefined ? {} : { assignmentVersion: version }),
    },
    ...opts,
  });
}

/* ----------------------------------------------------------- attendance --- */

/**
 * Cook-initiated check-in.
 *
 * The server owns the service date, the check-in timestamp and the on-time ruling. A replay
 * returns the ORIGINAL result with `created: false` — that is the "already present" response, and
 * it is a success, not an error.
 *
 * Rejections that are not failures of the app:
 *   `400` — no shift today, an approved leave today, or an existing non-present record
 *   `403` — the cook is not active
 */
export async function markPresent(
  idempotencyKey: string,
  opts: Opts = {},
): Promise<CookPresentResponse> {
  return request('/cook/attendance/present', cookPresentSchema, {
    method: 'POST',
    body: {},
    idempotencyKey,
    ...opts,
  });
}

/**
 * Month-scoped attendance.
 *
 * `scheduled` comes from `cook_shifts` and is returned SEPARATELY from `status`, so the app can
 * render the `Scheduled` legend entry without ever writing `scheduled` as an attendance status.
 * `onTimePercentage` is server-computed and is `null` when the month has no present days.
 */
export async function getMonthlyAttendance(
  month: string,
  opts: Opts = {},
): Promise<MonthlyAttendanceResponse> {
  return request('/cook/attendance/month', monthlyAttendanceSchema, {
    query: { month },
    ...opts,
  });
}

/**
 * Stored attendance records inside a window.
 *
 * Used by the cycle frame's Mon–Sun strip. A date absent from the response has NO record and is
 * rendered blank — inferring `absent` from absence would accuse a cook the server never marked.
 */
export async function listAttendanceRange(
  params: { readonly from: string; readonly to: string },
  opts: Opts = {},
): Promise<CookAttendanceRangeResponse> {
  return request('/cook/attendance', cookAttendanceRangeSchema, {
    query: { from: params.from, to: params.to },
    ...opts,
  });
}

/** Leave requests overlapping a window, grouped by request. Includes pending and rejected. */
export async function listLeaves(
  params: { readonly from?: string; readonly to?: string } = {},
  opts: Opts = {},
): Promise<CookLeavesResponse> {
  return request('/cook/leaves', cookLeavesSchema, {
    query: {
      ...(params.from === undefined ? {} : { from: params.from }),
      ...(params.to === undefined ? {} : { to: params.to }),
    },
    ...opts,
  });
}

/**
 * Submit a cook-initiated leave request.
 *
 * Deployed and verified: `POST /v1/cook/leaves` is registered on the live API. It answers `201`
 * with `status: 'pending'` — Ops/Admin still decide. The app must never render the leave as taken.
 *
 * Backend rejections that are not app failures:
 *   `400` — `startDate` in the past, or `endDate` before `startDate`
 *   `409` — an overlapping pending/approved leave already exists (`INVALID_BOOKING_STATE`)
 *   `403` — the cook is not active
 */
export async function requestLeave(
  input: {
    readonly startDateIso: string;
    readonly endDateIso: string;
    readonly reason?: string;
    readonly idempotencyKey: string;
  },
  opts: Opts = {},
): Promise<CookLeaveRequestResponse> {
  return request('/cook/leaves', cookLeaveRequestSchema, {
    method: 'POST',
    body: {
      startDate: input.startDateIso,
      endDate: input.endDateIso,
      ...(input.reason === undefined || input.reason.length === 0 ? {} : { reason: input.reason }),
    },
    idempotencyKey: input.idempotencyKey,
    ...opts,
  });
}

/* ------------------------------------------------------------- earnings --- */

/**
 * Daily, seven-day and current-cycle earnings plus bonus progress.
 *
 * Every figure is a server projection. The app formats paise and does no arithmetic — and the
 * bonus threshold arrives as `bonus.thresholdDays`, so no screen hardcodes 5, 7 or 27.
 */
export async function getEarnings(
  params: { readonly limit?: number } = {},
  opts: Opts = {},
): Promise<CookEarningsResponse> {
  return request('/cook/earnings', cookEarningsSchema, {
    query: { ...(params.limit === undefined ? {} : { limit: params.limit }) },
    ...opts,
  });
}

/**
 * One past service day's earnings.
 *
 * The same server-side breakdown `/cook/earnings` uses for its `daily` window, asked about a
 * different IST service date. It is deliberately NOT a client-side filter of the cycle's
 * `events[]`: reversals are their own signed category, so re-bucketing raw ledger rows here would
 * show a base figure the payout will not honour. The server refuses a future date.
 */
export async function getEarningsDay(
  serviceDate: string,
  opts: Opts = {},
): Promise<CookEarningsPeriodResponse> {
  return request(`/cook/earnings/day/${serviceDate}`, earningsPeriodSchema, opts);
}

export async function listEarningsCycles(
  params: { readonly limit?: number } = {},
  opts: Opts = {},
): Promise<CookCyclesResponse> {
  return request('/cook/earnings/cycles', cookCyclesSchema, {
    query: { ...(params.limit === undefined ? {} : { limit: params.limit }) },
    ...opts,
  });
}

/**
 * One past cycle.
 *
 * Deliberately NOT `cookEarningsSchema`: `getCookCycle` answers with `{ cycleId, startDate,
 * endDate, status, breakdown, summary, totalPaise, events }`. Validating it against the
 * `/cook/earnings` schema — as an earlier build did — fails on every response.
 */
export async function getEarningsCycle(
  cycleId: string,
  opts: Opts = {},
): Promise<CookCycleDetailResponse> {
  return request(`/cook/earnings/cycles/${cycleId}`, cookCycleDetailSchema, opts);
}

/**
 * The WEEKS a cook has earned in — what the Kamai screens call a cycle.
 *
 * Separate from `listEarningsCycles`, which returns the 28-day PAYOUT periods the attendance
 * bonuses resolve over. The two share a word and nothing else.
 */
export async function listEarningsWeeks(
  params: { readonly limit?: number } = {},
  opts: Opts = {},
): Promise<CookWeeksResponse> {
  return request('/cook/earnings/weeks', cookWeeksSchema, {
    query: { ...(params.limit === undefined ? {} : { limit: params.limit }) },
    ...opts,
  });
}

/** One week. Any day of it resolves to the whole week server-side. */
export async function getEarningsWeek(
  startDate: string,
  opts: Opts = {},
): Promise<CookWeekDetailResponse> {
  return request(`/cook/earnings/weeks/${startDate}`, cookWeekDetailSchema, opts);
}

/* -------------------------------------------------------------- devices --- */

/** Register this device for push. The token is a secret and is never logged or echoed. */
export async function registerPushToken(
  input: { readonly token: string; readonly platform: 'android' | 'ios' },
  opts: Opts = {},
): Promise<void> {
  await request('/me/push-token', commandAckSchema, {
    method: 'PUT',
    body: { token: input.token, platform: input.platform },
    ...opts,
  });
}
