/**
 * Pin the Android NDK version across every native subproject.
 *
 * ## Why this plugin has to exist
 *
 * React Native 0.86.2's `ReactCommon/react/renderer/core/graphicsConversions.h:71` calls
 * `std::format`. NDK **27.1.12297006** ships a libc++ without `<format>`, so every native module
 * that includes that header fails to compile:
 *
 *     error: no member named 'format' in namespace 'std'
 *
 * It is reached through `ViewProps.h` → `HostPlatformViewProps.h` → `NativeDrawable.h`, so this
 * takes down `react-native-reanimated`, `react-native-worklets` and `expo-modules-core` — i.e. the
 * build, not one optional module.
 *
 * `expo-root-project` defaults `ndkVersion` to exactly that broken version
 * (`ExpoRootProjectPlugin.kt`: `versionCatalogs.getVersionOrDefault("ndkVersion", "27.1.12297006")`),
 * so a default Expo SDK 57 / RN 0.86 Android build cannot succeed on a machine whose newest NDK is
 * 27.1. NDK **27.2.12479018** provides `__cpp_lib_format` and builds cleanly.
 *
 * ## Why `rootProject.ext.ndkVersion` is the correct lever
 *
 * That same Expo plugin reads the property through `setIfNotExist`:
 *
 *     val ndk = extra.setIfNotExist("ndkVersion") { ...getVersionOrDefault("ndkVersion", "27.1...") }
 *
 * `setIfNotExist` is an explicit extension point: a value already present on `rootProject.ext` is
 * kept, and the default is only computed when nothing set one. Writing the property **before**
 * `apply plugin: "expo-root-project"` therefore overrides the default through the supported path
 * rather than fighting it.
 *
 * Every native module in this project then picks it up on its own, because they all guard on the
 * same property:
 *
 *   - `react-native-reanimated/android/build.gradle.kts`  — `if (rootProject.hasProperty("ndkVersion"))`
 *   - `react-native-worklets/android/build.gradle.kts`    — same
 *   - `expo-modules-core/android/build.gradle`            — same
 *   - `react-native-screens`, `react-native-gesture-handler`, `react-native-svg` — same
 *
 * An earlier iteration forced the version with a `subprojects { afterEvaluate { android { … } } }`
 * block. That worked but was a blunt instrument: it reached into every Android subproject's
 * extension after evaluation, which is both broader than necessary and easy to break when a module
 * configures its own NDK deliberately. Setting the one property the modules already read is
 * smaller, and it is what they were written to respect.
 *
 * ## Why a config plugin rather than editing `android/`
 *
 * `android/` is generated and gitignored. `expo prebuild --clean` deletes it, so a hand edit there
 * survives exactly until the next clean prebuild and then silently reverts to the broken default.
 * This plugin re-applies the pin on every prebuild, which is what makes the build reproducible.
 *
 * `expo-build-properties` is NOT used: its documented Android API covers `compileSdkVersion`,
 * `targetSdkVersion`, `minSdkVersion`, `buildToolsVersion` and friends — it does not expose
 * `ndkVersion`. Depending on an undocumented field would be a worse guarantee than this.
 *
 * @param {import('@expo/config-plugins').ExpoConfig} config
 * @param {{ ndkVersion: string }} props
 */

const { withProjectBuildGradle } = require('@expo/config-plugins');

/** Marks the injected block so re-running prebuild replaces it instead of stacking copies. */
const MARKER = '// @generated by withAndroidNdkVersion';

/** The line the Expo root plugin is applied on. The pin must land before it. */
const EXPO_ROOT_APPLY = 'apply plugin: "expo-root-project"';

const NDK_VERSION_PATTERN = /^\d+\.\d+\.\d+$/;

/**
 * Remove a previously injected block, so the plugin is idempotent across repeated prebuilds and
 * across a version change.
 */
function stripExistingBlock(contents) {
  // Matches the marker line through the closing brace of the `ext { … }` block it introduces.
  const block = new RegExp(`\\n*${MARKER}[\\s\\S]*?\\n\\}\\n`, 'g');
  return contents.replace(block, '\n');
}

function buildBlock(ndkVersion) {
  return [
    '',
    MARKER,
    '// Pinned because RN 0.86 needs a libc++ with <format>; the Expo root plugin would',
    '// otherwise default to 27.1.12297006, which lacks it. This block is emitted ahead of',
    '// that plugin so its `setIfNotExist("ndkVersion")` keeps this value, and every native',
    '// module that reads `rootProject.ext.ndkVersion` inherits it.',
    'ext {',
    `  ndkVersion = "${ndkVersion}"`,
    '}',
    '',
  ].join('\n');
}

/**
 * @type {import('@expo/config-plugins').ConfigPlugin<{ ndkVersion: string }>}
 */
const withAndroidNdkVersion = (config, props) => {
  const ndkVersion = props?.ndkVersion;

  if (typeof ndkVersion !== 'string' || !NDK_VERSION_PATTERN.test(ndkVersion)) {
    // Failing loudly is deliberate. A silently skipped pin produces a build that dies thousands of
    // lines into a C++ compile with an error that looks nothing like a configuration mistake.
    throw new Error(
      `withAndroidNdkVersion: expected a full NDK version like "27.2.12479018", received ${JSON.stringify(
        ndkVersion,
      )}.`,
    );
  }

  return withProjectBuildGradle(config, (mod) => {
    if (mod.modResults.language !== 'groovy') {
      throw new Error(
        `withAndroidNdkVersion: expected a Groovy android/build.gradle, found "${mod.modResults.language}".`,
      );
    }

    let contents = stripExistingBlock(mod.modResults.contents);

    if (!contents.includes(EXPO_ROOT_APPLY)) {
      throw new Error(
        `withAndroidNdkVersion: could not find \`${EXPO_ROOT_APPLY}\` in android/build.gradle. ` +
          'The generated template changed; re-check where ndkVersion must be set.',
      );
    }

    // Insert immediately before the Expo root plugin is applied — `setIfNotExist` only preserves a
    // value that already exists at that moment.
    contents = contents.replace(EXPO_ROOT_APPLY, `${buildBlock(ndkVersion)}\n${EXPO_ROOT_APPLY}`);

    mod.modResults.contents = contents;
    return mod;
  });
};

module.exports = withAndroidNdkVersion;
// Exported for unit tests, which exercise the string transform without running prebuild.
module.exports.MARKER = MARKER;
module.exports.stripExistingBlock = stripExistingBlock;
module.exports.buildBlock = buildBlock;
