/**
 * Figma V14 vector icons, inlined verbatim from the committed exports.
 *
 * GENERATED by `python scripts/visual/build_icons.py` — do not edit by hand. Each string
 * is the exact content of the matching file in `assets/images/figma-v14/`, which is the
 * original Figma export; re-running the generator must produce no diff.
 *
 * Render with `SvgXml` from `react-native-svg`. The project has no SVG Metro transformer,
 * so the markup has to reach the bundle as source rather than as an import — handing the
 * `.svg` to an `<Image>` renders nothing on Android.
 */

/** `back.svg` — Figma nodes: 592:488. */
export const back =
  '<svg preserveAspectRatio="none" overflow="visible" style="display: block;" width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g id="back" clip-path="url(#clip0_0_4)">\n<g id="Ellipse 1" filter="url(#filter0_d_0_4)">\n<circle cx="16" cy="16" r="14" fill="white"/>\n<circle cx="16" cy="16" r="13.5" stroke="black" stroke-opacity="0.15"/>\n</g>\n<path id="Vector" d="M18.6667 22.6667L12 16L18.6667 9.33333" stroke="black" stroke-opacity="0.7" stroke-width="1.66667" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<filter id="filter0_d_0_4" x="-2" y="-2" width="36" height="36" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">\n<feFlood flood-opacity="0" result="BackgroundImageFix"/>\n<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>\n<feOffset/>\n<feGaussianBlur stdDeviation="2"/>\n<feComposite in2="hardAlpha" operator="out"/>\n<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.07 0"/>\n<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_0_4"/>\n<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_0_4" result="shape"/>\n</filter>\n<clipPath id="clip0_0_4">\n<rect width="32" height="32" fill="white"/>\n</clipPath>\n</defs>\n</svg>';

/** `call-icon.svg` — Figma nodes: 614:453. */
export const callIcon =
  '<svg preserveAspectRatio="none" overflow="visible" style="display: block;" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g id="Frame" clip-path="url(#clip0_0_20)">\n<path id="Vector" d="M9.2824 11.5959C9.42697 11.6671 9.58984 11.6833 9.74418 11.642C9.89853 11.6007 10.0351 11.5043 10.1315 11.3687L10.38 11.0199C10.5104 10.8336 10.6795 10.6824 10.8739 10.5783C11.0683 10.4741 11.2827 10.4199 11.5 10.4199H13.6C13.9713 10.4199 14.3274 10.578 14.5899 10.8593C14.8525 11.1406 15 11.5221 15 11.9199V14.1699C15 14.5677 14.8525 14.9493 14.5899 15.2306C14.3274 15.5119 13.9713 15.6699 13.6 15.6699C10.2583 15.6699 7.05341 14.2476 4.69045 11.7159C2.3275 9.18412 1 5.75034 1 2.16992C1 1.7721 1.1475 1.39057 1.41005 1.10926C1.6726 0.827957 2.0287 0.669922 2.4 0.669922H4.5C4.8713 0.669922 5.2274 0.827957 5.48995 1.10926C5.7525 1.39057 5.9 1.7721 5.9 2.16992V4.41992C5.9 4.65279 5.8494 4.88246 5.7522 5.09074C5.655 5.29903 5.51387 5.4802 5.34 5.61992L5.0124 5.88317C4.88389 5.98831 4.79331 6.13786 4.75605 6.30643C4.71879 6.47501 4.73715 6.6522 4.808 6.80792C5.76468 8.88982 7.3381 10.5735 9.2824 11.5959Z" stroke="black" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<clipPath id="clip0_0_20">\n<rect width="16" height="16" fill="white"/>\n</clipPath>\n</defs>\n</svg>';

/** `info-back.svg` — Figma nodes: 597:1221. */
export const infoBack =
  '<svg preserveAspectRatio="none" overflow="visible" style="display: block;" width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g id="Frame" clip-path="url(#clip0_0_4)">\n<g id="Ellipse 1" filter="url(#filter0_d_0_4)">\n<circle cx="16" cy="16" r="14" fill="white"/>\n<circle cx="16" cy="16" r="13.5" stroke="black" stroke-opacity="0.15"/>\n</g>\n<path id="Vector" d="M18.6667 22.6667L12 16L18.6667 9.33333" stroke="black" stroke-opacity="0.7" stroke-width="1.66667" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<filter id="filter0_d_0_4" x="-2" y="-2" width="36" height="36" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">\n<feFlood flood-opacity="0" result="BackgroundImageFix"/>\n<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>\n<feOffset/>\n<feGaussianBlur stdDeviation="2"/>\n<feComposite in2="hardAlpha" operator="out"/>\n<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.15 0"/>\n<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_0_4"/>\n<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_0_4" result="shape"/>\n</filter>\n<clipPath id="clip0_0_4">\n<rect width="32" height="32" fill="white"/>\n</clipPath>\n</defs>\n</svg>';

/** `map-pin.svg` — Figma nodes: 614:453. */
export const mapPin =
  '<svg preserveAspectRatio="none" overflow="visible" style="display: block;" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g id="Frame" clip-path="url(#clip0_0_22)">\n<path id="Vector" d="M0.5 7.77519L15.5 0.669922L8.39474 15.6699L6.81579 9.35413L0.5 7.77519Z" stroke="black" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<clipPath id="clip0_0_22">\n<rect width="16" height="16" fill="white"/>\n</clipPath>\n</defs>\n</svg>';

/** `mistake-disc.svg` — Figma nodes: 575:1744. */
export const mistakeDisc =
  '<svg preserveAspectRatio="none" overflow="visible" style="display: block;" width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">\n<circle id="Ellipse 2" cx="14" cy="14" r="14" fill="white"/>\n</svg>';

/** `rating-disc.svg` — Figma nodes: 575:1744. */
export const ratingDisc =
  '<svg preserveAspectRatio="none" overflow="visible" style="display: block;" width="38" height="38" viewBox="0 0 38 38" fill="none" xmlns="http://www.w3.org/2000/svg">\n<circle id="Ellipse 3" cx="19" cy="19" r="19" fill="white"/>\n</svg>';
